import type { ItineraryItem } from "@shared/schema";

export const mockItineraryData: ItineraryItem[] = [
  {
    id: "item1",
    userId: "demo-user",
    day: 1,
    title: "Morning at Senso-ji Temple",
    description: "Experience the spiritual heart of Tokyo at this ancient Buddhist temple. Perfect for morning meditation and photography.",
    imageUrl: "https://images.unsplash.com/photo-1542640244-7e672d6cef4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    startTime: "8:00 AM",
    endTime: "10:00 AM",
    category: "Cultural",
    cost: 0,
    duration: "2 hours",
    tags: ["Cultural", "Free"],
    isCompleted: false,
    isFavorited: false,
  },
  {
    id: "item2",
    userId: "demo-user",
    day: 1,
    title: "Tsukiji Fish Market Food Tour",
    description: "Discover the freshest sushi and local delicacies in this iconic market. Guided tour includes tastings at 5 different stalls.",
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    startTime: "11:00 AM",
    endTime: "2:00 PM",
    category: "Food",
    cost: 85,
    duration: "3 hours",
    tags: ["Food", "$85"],
    isCompleted: false,
    isFavorited: false,
  },
  {
    id: "item3",
    userId: "demo-user",
    day: 1,
    title: "Shibuya Crossing & Local Bar",
    description: "Experience the world's busiest intersection, then discover a hidden izakaya known only to locals for authentic drinks and atmosphere.",
    imageUrl: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    startTime: "7:00 PM",
    endTime: "11:00 PM",
    category: "Nightlife",
    cost: 40,
    duration: "4 hours",
    tags: ["Nightlife", "$40"],
    isCompleted: false,
    isFavorited: false,
  },
];
